// src/components/studio/tools/IdeaBuilderTool.jsx
import React from "react";

export default function IdeaBuilderTool({ onInsert }) {
  return (
    <div style={{ padding: 12 }}>
      <h3>Idea Builder</h3>
      <p>Generate idea summary, features & next steps.</p>
      <button onClick={() => onInsert("New idea generated by Idea Builder")}>Insert into canvas</button>
    </div>
  );
}
